definitions:
  default_environments: &default_environments
    node: 16.14.2
    npm: latest
  scripts:
    - &setup_private_config
      name: Setup private config files
      script: cp src/private_config.example src/private_config.ts
    - &yarn_install
      name: Yarn install
      script: yarn install
    - &run_linter
      name: Run linter
      script: yarn lint
    - &compile_typescript
      name: Run typescript compiler
      script: yarn tsc
    - &yarn_test
      name: Yarn test
      script: yarn test

workflows:
  static-checks:
    name: Static checks
    max_build_duration: 60
    environment:
      <<: *default_environments
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: false
      cancel_previous_builds: true
    scripts:
      - *yarn_install
      - *setup_private_config
      - *run_linter
      - *compile_typescript
    publishing:
      slack:
        channel: '#ci-builds'
